# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sean Hofer
email: me@seanhofer.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal professional site of Sean Hofer, Front-End Web Developer in the San Francisco Bay Area
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://seanhofer.com" # the base hostname & protocol for your site, e.g. http://example.com
address: "https://seanhofer.com"
github_username: hofers
resume:
  pdf: /assets/Sean Hofer - Resume.pdf
  docx: /assets/Sean Hofer - Resume.docx

defaults:
  -
    scope:
      path: "" 
      type: "pages" 
    values:
      layout: "page"
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      layout: "post"

# This sets the default permalink for blog posts
permalink: /class-blog/:title

sass:
  sass_dir: _sass
  style: compressed

collections:
  portfolio-items:
    sort_by: date
  press-items:

# Build settings
plugins:
  - jekyll-brotli
  - jekyll-redirect-from
  - jekyll-replace-last
  - jemoji

# Serve settings
host: 0.0.0.0

jekyll-uglify:
  harmony: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
