# Name of your GitHub Actions workflow.
name: Publish to GitHub Pages

# Specifies to run this workflow whenever a push is made (commits are
# added) to the branch named `jekyll`.
on:
  push:
    branches:
      # Change this to the branch where you keep your Jekyll code.
      - jekyll

# Define a job named `build-and-publish` in your workflow.
jobs:
  build-and-publish:
    runs-on: ubuntu-latest # This job uses a GitHub-hosted runner.

    steps:
      # Checkout the source from the `jekyll` branch.
      - uses: actions/checkout@v2
        with:
          persist-credentials: false 
          fetch-depth: 0
      
      # Ruby / bundle setup
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.6
      - run: bundle install

      # Uglify JS
      - name: Uglify JS
        run: bundle exec jekyll uglify /_includes/scripts/
        
      # Build
      - run: JEKYLL_ENV=production bundle exec jekyll build
        
      # Replace directory with _site
      - name: Replace directory with _site
        run: |
          find . ! \( -iregex '^./_site.*' -or -iregex '^./.git' -or -iregex '^./.git[^h].*' \) -delete
          rsync -r _site/ .

      # Add, commit, and push
      - name: Add and commit
        run: |
          git config --global user.email "me@seanhofer.com"
          git config --global user.name "hofers"
          git add --all
          git commit -m "Built and deployed Jekyll"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JEKYLL_PAT }}
          force: true
