name: Publish to GitHub Pages

on:
  push:
    branches:
      - jekyll

jobs:
  build-and-publish:
    runs-on: ubuntu-latest 

    steps:
      # Checkout the source from the `jekyll` branch.
      - uses: actions/checkout@v2
        with:
          persist-credentials: false 
          fetch-depth: 0
      
      # Ruby / bundle setup
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.6
      - run: bundle install

      # Uglify JS
      - name: Uglify JS
        run: bundle exec jekyll uglify _includes/scripts

      # Create webp images
      - name: Create webp images
        run: |
          sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libgif-dev
          cd bin
          tar xvzf libwebp-1.1.0.tar.gz
          cd libwebp-1.1.0
          ./configure
          make
          sudo make install
          cd ../../assets/images/
          ../../bin/cwebp-dir.sh
          cd class-blog
          ../../../bin/cwebp-dir.sh
        
      # Build
      - run: JEKYLL_ENV=production bundle exec jekyll build
        
      # Replace directory with _site
      - name: Replace directory with _site
        run: |
          find . ! \( -iregex '^./_site.*' -or -iregex '^./.git' -or -iregex '^./.git[^h].*' \) -delete
          rsync -r _site/ .

      # Add, commit, and push
      - name: Add and commit
        run: |
          git config --global user.email "me@seanhofer.com"
          git config --global user.name "hofers"
          git add --all
          git commit -m "Built and deployed Jekyll"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JEKYLL_PAT }}
          force: true
