# Name of your GitHub Actions workflow.
name: Publish to GitHub Pages

# Specifies to run this workflow whenever a push is made (commits are
# added) to the branch named `jekyll`.
on:
  push:
    branches:
      # Change this to the branch where you keep your Jekyll code.
      - jekyll

# Define a job named `build-and-publish` in your workflow.
jobs:
  build-and-publish:
    runs-on: ubuntu-latest # This job uses a GitHub-hosted runner.

    steps:
      # Checkout the source from the `jekyll` branch.
      - uses: actions/checkout@v2
      
      # Ruby / bundle setup
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.6
      - run: gem install bundler
      - run: bundle install
        
      # Build
      - run: bundle exec jekyll build
        
      # Replace directory with _site
      - run: shopt -s extglob
      - run: rm -r !(_site)
      - run: cp -a /_site/. .

      # Add, commit, and push
      - run: git add .
      - run: git commit -m "Built and deployed Jekyll"
      - run: git push origin master
